# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bundler', '2.4.10'
gem 'help_me_decide', path: '../gem'
gem 'minitest', group: :test
gem 'puma'
gem 'rack-test', group: :test
gem 'rake', group: :test
gem 'rubocop', group: 'development'
gem 'simplecov', require: false, group: :test
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'
